# Netlify configuration file

[build]
  # Command to build the project
  command = "yarn build"
  # Directory to publish
  publish = "dist"

# Redirect rule for Single-Page Applications (SPAs)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
