# Netlify configuration file

[build]
  # Command to build the project
  command = "yarn build"
  # Directory where the built files are located
  publish = "dist"

# Redirect rule for Single-Page Applications (SPAs)
# This ensures that all routes are handled by index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
